default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /tmp/mysql.sock

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: protospace_42425_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: protospace_42425_test


production:
  <<: *default
  adapter: postgresql
  ulr: <%= ENV['DATABASE_URL'] %>
